export const nations = [
  { code: 'BR', name: 'Brazil', search: 'BR' },
  { code: 'DE', name: 'Germany', search: 'GER' },
  { code: 'AR', name: 'Argentina', search: 'ARG' },
  { code: 'FR', name: 'France', search: 'FR' },
  { code: 'IT', name: 'Italy', search: 'IT' },
  { code: 'ES', name: 'Spain', search: 'ESP' },
  { code: 'NL', name: 'Netherlands', search: 'NL' },
  { code: 'PT', name: 'Portugal', search: 'PT' },
  { code: 'BE', name: 'Belgium', search: 'BE' },
  { code: 'UY', name: 'Uruguay', search: 'UY' },
  { code: 'CO', name: 'Colombia', search: 'COL' },
  { code: 'MX', name: 'Mexico', search: 'MX' },
  { code: 'US', name: 'United States', search: 'USA' },
  { code: 'JP', name: 'Japan', search: 'JP' },
  { code: 'KR', name: 'South Korea', search: 'KR' },
  { code: 'IE', name: 'Ireland', search: 'IRL' },
  { code: 'AU', name: 'Australia', search: 'AUS' },
];
